/**
 * Typed registry of pending MCP auth prompts awaiting a renderer response.
 * It is owned by exactly one profile-bound `McpAuthService`; the IPC handler
 * resolves the sender's `MCPClientManager` first, then dispatches into this
 * instance. No process-global prompt state exists.
 *
 * Two independent maps because the response shapes are disjoint:
 *
 *   - **Consent** (`mcpAuth:showConsent` ↔ `mcpAuth:respondConsent`):
 *     yes/no decision.
 *   - **Client-id** (`mcpAuth:requestClientId` ↔ `mcpAuth:respondClientId`):
 *     either `{ cancelled: true }` or `{ clientId, clientSecret? }`.
 *
 * Keys are ephemeral request ids generated by `McpAuthService`. Handlers
 * are one-shot — they `delete` themselves after firing or being timed
 * out / aborted (handled inside `McpAuthService`).
 */

import type { McpAuthClientIdResponse } from '../../../../shared/types/mcpAuth';

export type McpAuthConsentDecision = 'cancel' | 'allow-this-time';
export type ConsentHandler = (decision: McpAuthConsentDecision) => void;
export type ClientIdHandler = (response: McpAuthClientIdResponse) => void;

/**
 * 一个 MCP runtime Profile 对应一个 registry。响应由 sender 所属的
 * MCPClientManager 直接消费，因而不需要进程级 handler map 或 profileId 二次筛选。
 */
export class McpAuthPromptRegistry {
  private readonly consentHandlers = new Map<string, ConsentHandler>();
  private readonly clientIdHandlers = new Map<string, ClientIdHandler>();

  registerConsent(requestId: string, handler: ConsentHandler): void {
    this.consentHandlers.set(requestId, handler);
  }

  takeConsent(requestId: string): ConsentHandler | undefined {
    const handler = this.consentHandlers.get(requestId);
    if (!handler) return undefined;
    this.consentHandlers.delete(requestId);
    return handler;
  }

  cancelConsent(requestId: string): void {
    this.consentHandlers.delete(requestId);
  }

  registerClientId(requestId: string, handler: ClientIdHandler): void {
    this.clientIdHandlers.set(requestId, handler);
  }

  takeClientId(requestId: string): ClientIdHandler | undefined {
    const handler = this.clientIdHandlers.get(requestId);
    if (!handler) return undefined;
    this.clientIdHandlers.delete(requestId);
    return handler;
  }

  cancelClientId(requestId: string): void {
    this.clientIdHandlers.delete(requestId);
  }

  // ────────────────── Test-only helpers ──────────────────

  /** Test-only: list pending consent request ids (enumeration order). */
  __listConsentIdsForTests(): string[] {
    return Array.from(this.consentHandlers.keys());
  }

  /** Test-only: list pending client-id request ids. */
  __listClientIdIdsForTests(): string[] {
    return Array.from(this.clientIdHandlers.keys());
  }
}
